import { Geist, Geist_Mono, Sora } from "next/font/google";
import "./globals.css";
import Navbar from "./components/shared/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

export const metadata = {
  title: "PrintEra Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sora.className} antialiased max-w-[1200px] mx-auto`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
